# Deploys the configuration stored in /auth0/tenant.yaml
name: Deploy Auth0
on:
    workflow_dispatch:
        inputs:
            deploy_env:
                required: true
                description: The environment to deploy to
                type: choice
                options:
                    - staging
                    - production
                default: staging

jobs:
    deploy:
        uses: ./.github/workflows/template.auth0-deploy.yml
        with:
            auth0_env: ${{ github.event.inputs.deploy_env }}
        secrets:
            client_secret: ${{ (github.event.inputs.deploy_env == 'production' && secrets.PROD_AUTH0_CLIENT_SECRET) || (github.event.inputs.deploy_env == 'staging' && secrets.STAGING_AUTH0_CLIENT_SECRET) }}
            postmark_secret: ${{ secrets.POSTMARK_SMTP_PASS }}
            apple_secret: ${{ secrets.APPLE_SIGN_IN_SECRET_KEY }}
