# Deploys the configuration stored in /auth0/tenant.yaml
name: TEMPLATE | Deploy Auth0
on:
    workflow_call:
        inputs:
            auth0_env:
                description: Tenant to deploy to.  Valid values are `staging | production`
                type: string
                required: true
        secrets:
            client_secret:
                required: true
            postmark_secret:
                required: true
            apple_secret:
                required: true

concurrency:
    group: auth0_deployments
    cancel-in-progress: false

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '18'
            - run: yarn install --frozen-lockfile
            - name: Deploy Auth0 resources
              env:
                  AUTH0_DEPLOY_CLIENT_SECRET: ${{ secrets.client_secret }}
                  POSTMARK_SMTP_PASS: ${{ secrets.postmark_secret }}
                  APPLE_SIGN_IN_SECRET_KEY: ${{ secrets.apple_secret }}
                  AUTH0_ENV: ${{ inputs.auth0_env }}
              run: yarn auth0:deploy
